name: Build And Publish Releases

# https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
permissions:
  contents: write

on:
  # Allow mannual trigger
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: latest
          dest: dist
          prefix: clash2singbox
          targets: windows/amd64,linux/amd64,linux/arm,linux/arm64
          # Show less information
          v: false
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: latest
          tag: latest
          file_glob: true
          file: ./dist/*
